[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_api/:splat"
  status = 200

[functions]
  directory = ".netlify/functions/"
  included_files = [".next/standalone/**", ".next/static/**"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
